### PR TITLE
Use NativeLibrary.Load instead of dlopen

### LINKED ISSUE #288: Unable to Load Shared Library 'libdl' or one of it's dependencies
SharpPcap Version: 6.0.0.
.NET Version: Core 3.1
OS: Ubuntu 20.04.2 LTS

I have some C# code that uses SharpPcap, it works on Windows but on Linux I'm having trouble getting it to get past the "CaptureDevices.List.Instance part of the code. 

The code compiles without errors or warning but throws this DLL error when running.  Any idea what this could be?  I can't find much online about this error.  

SharpPcap 6.0.0.0, Example4.BasicCapNoCallback.cs

Unhandled exception. System.DllNotFoundException: Unable to load shared library 'libdl' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: liblibdl: cannot open shared object file: No such file or directory
   at SharpPcap.LibPcap.LibPcapSafeNativeMethods.dlopen(String filename, Int32 flags)
   at SharpPcap.LibPcap.LibPcapSafeNativeMethods.Resolver(String libraryName, Assembly assembly, Nullable`1 searchPath)
   at System.Runtime.InteropServices.NativeLibrary.LoadLibraryCallbackStub(String libraryName, Assembly assembly, Boolean hasDllImportSearchPathFlags, UInt32 dllImportSearchPathFlags)
   at SharpPcap.LibPcap.LibPcapSafeNativeMethods.pcap_findalldevs(IntPtr& alldevs, StringBuilder errbuf)
   at SharpPcap.LibPcap.PcapInterface.GetAllPcapInterfaces()
   at SharpPcap.LibPcap.LibPcapLiveDeviceList.GetDevices()
   at SharpPcap.LibPcap.LibPcapLiveDeviceList.Refresh()
   at SharpPcap.LibPcap.LibPcapLiveDeviceList..ctor()
   at SharpPcap.LibPcap.LibPcapLiveDeviceList.get_Instance()
   at SharpPcap.CaptureDeviceList..ctor()
   at SharpPcap.CaptureDeviceList.get_Instance()

### PR DESCRIPTION
**Pull request by kayoub5**
Fixes #288

### CODE REVIEW

**Comment by kayoub5** [comment]
@escservices, @samuel-pl,

I can not reproduce the issue you got in #288, but this PR removes `libdl` as a dependency.
Could you cross check?

**Comment by kayoub5** [comment]
@chmorgan I couldn't find the missing coverage codecov is reporting, I just moved code around, and the `TryLoad` method I added is covered.
Got any clues?

**Comment by kayoub5** [comment]
@chmorgan review?

**Comment by chmorgan** [comment]
Sorry for the delay, let me review today.

This fixes the issues with missing libld?

**Comment by kayoub5** [comment]
> Sorry for the delay, let me review today. This fixes the issues with missing libld?

Yes

**Review by chmorgan — APPROVED** [review]

**Comment by genghis69** [comment]
Hello, I am writing to you because I am experiencing a problem that prevents a compilation on visual studio 2019 vb.net, I have this as an error : 'PacketCapture' is obsolete : 'Types with embedded references are not supported in this version of your compiler.'

Does anyone have a solution for this problem? thank you in advance 

PS: I use visual studio 2019
Language : vb.net

Thank you for your help

**Comment by kayoub5** [comment]
@genghis69 please create separate issue, your problem have nothingto do with this PR.

**Pull request merged**
