### PR TITLE
IpHelperTest - Test fixture for IpHelper class

### PR DESCRIPTION
**Pull request by chmorgan**

### CODE REVIEW

**Comment by chmorgan** [comment]
@kayoub5 crash reason here is entirely a mystery to me. Thoughts?

**Comment by kayoub5** [comment]
@chmorgan I think you just found the reason why the WinDivert sending tests where failing, it seems it was caused by `GetBestRoute2` marshalling, I will look into it later.

**Comment by kayoub5** [comment]
@chmorgan I pushed the fix, it should also fix windivert sending tests.

**Comment by chmorgan** [comment]
@kayoub5 this makes a ton of sense. I presume it was too small previously? I guess tests do help :-) I'll merge when you approve.

**Review by kayoub5 — APPROVED** [review]

**Pull request merged**
