### PR TITLE
Remove WinPcap namespace.

### PR DESCRIPTION
**Pull request by kayoub5**

### CODE REVIEW

**Comment by chmorgan** [comment]
@kayoub5 this overlaps with a pending PR I have open, https://github.com/chmorgan/sharppcap/pull/195.

**Comment by kayoub5** [comment]
@chmorgan #195 has too many changes for one PR, I extracted the part about removing WinPcap into its own PR.

**Comment by chmorgan** [comment]
@kayoub5 that's probably the case. The commit doesn't look extracted as its authorship is listed as you. I can certainly pull out the commit and push it to a separate PR but it entirely screws the review process if I have to wonder if its identical to the commit I proposed (and hence already reviewed) or not.

**Comment by chmorgan** [comment]
@kayoub5 eg, if you think a commit should be split off it would reduce effort the most to ask or cherry-pick that commit out so its content remained the same. Then I wouldn't have to review it.

**Comment by kayoub5** [comment]
@chmorgan I rewrote the PR history to include your commit with you as author, second commit is for files you did not delete in the first commit.

**Comment by chmorgan** [comment]
@kayoub5 and I apologize if I sound testy. I don't often get the time or urge to really crank away at cleaning this stuff up and it pains me if we overlap efforts. If you'd like to stake claim to something that isn't already on the v6 pr branch or related to optional parameters please do so and I'll stay away and msg before I consider digging in there.

**Pull request closed without merging**
