### PR TITLE
Add support for WinpkFilter

### PR DESCRIPTION
**Pull request by kayoub5**
Add support for the WinpkFilter from https://www.ntkernel.com/windows-packet-filter/

### CODE REVIEW

**Comment by kayoub5** [comment]
@chmorgan any changes I should make before I start writing unit tests?

**Comment by chmorgan** [comment]
This looks pretty cool @kayoub5. I think I might have used this capture library/driver for a commercial product many years ago. This for a project of yours? I was curious about the use case vs. say windivert.

**Review by chmorgan — APPROVED** [review]

**Comment by chmorgan** [comment]
@kayoub5 and approval is to indicate yep, tests make sense as next step I think. I mean, unless you think we shouldn't consider adding additional capture frameworks to sharppcap, imo they fit in relatively well and make sense to support a number of them as we've got people to support them.

**Comment by kayoub5** [comment]
> This looks pretty cool @kayoub5. I think I might have used this capture library/driver for a commercial product many years ago. This for a project of yours? I was curious about the use case vs. say windivert.

Nope, I am not affiliated with neither projects, it's just that different users will have different needs, WinDivert operates on the IP layer, WinpkFilter operates on the Ethernet layer.

**Comment by kayoub5** [comment]
@chmorgan it seems the WinpkFilter driver requires reboot to work...
Now what?

**Comment by chmorgan** [comment]
Hmm. Reboot after being installed on windows? That would seem to prevent us
from doing CI if each instance is wiped out after each CI run.

**Comment by kayoub5** [comment]
> 
> Hmm. Reboot after being installed on windows? That would seem to prevent us from doing CI if each instance is wiped out after each CI run.

Yeah, circle CI seems to hang during install of driver, azure and appveyor passed the install, so we are good

**Comment by kayoub5** [comment]
@chmorgan I am getting this error in azure
https://dev.azure.com/chmorgan/chmorgan/_build/results?buildId=826&view=logs&j=0da5d1d9-276d-5173-c4c4-9d4d4ed14fdb&t=5b4cc83a-7bb0-5664-5bb1-588f7e4dc05b&l=136
```
{'detail': ErrorDetail(string='Unable to locate build via Azure API. Project is likely private, please upload with the Codecov repository upload token to resolve issue.', code='not_found')}
```
Could you renew/check the codecov tokens?

**Comment by kayoub5** [comment]
@chmorgan 
New type of error from azure

> No hosted parallelism has been purchased or granted. To request a free parallelism grant, please fill out the following form https://aka.ms/azpipelines-parallelism-request

**Comment by chmorgan** [comment]
@kayoub5 it doesn't look like the Codecov token has expired.  I also can't figure out where that parallelism setting is located. I saw one under my own account, maybe that's the one? It says 1 right now.

**Comment by kayoub5** [comment]
> @kayoub5 it doesn't look like the Codecov token has expired. I also can't figure out where that parallelism setting is located. I saw one under my own account, maybe that's the one? It says 1 right now.

for parallelism you need to fill out the form in the link.

for the token check the environment variables configuration in azure.

**Comment by chmorgan** [comment]
@kayoub5 filled out the form in the link, no idea why this is showing up now though. We didn't request parallelism did we??

**Comment by chmorgan** [comment]
Oh and I confirmed the token looks fine. It might be unrelated or related to the other build issues. I'll take another look when we can build again on azure.

**Comment by chmorgan** [comment]
@kayoub5 did you end up setting the Codecov token? I see the global in the semaphore configuration file but not in the cloud side configuration.

**Comment by chmorgan** [comment]
@kayoub5 oh never mind, I see it now. The screen with 'Setup global tokens' lead me to believe there were no tokens configured. Tried clicking there and I see it now.

**Comment by kayoub5** [comment]
@chmorgan final review?

**Review by chmorgan — APPROVED** [review]
Looks ok to me!

**Pull request merged**
