### PR TITLE
Rename WinPcapDevice to NPcapDevice

### PR DESCRIPTION
**Pull request by juyanith**
This is for issue #81. I think I've found all the winpcap references but there are a couple of things I'm not sure about. 
1. There are still references to www.winpcap.org documentation. I checked that they are still currently valid but I don't know if there are newer npcap versions.
2. There are some references to rpcapd. I don't have those on my machine so I'm not sure what to do with them.
I hope this is helpful.

### CODE REVIEW

**Comment by lextm** [comment]
It is very bad idea to perform such renaming, and also surprised that it was merged. Renaming namespaces and classes simply break any code depending on them.

Instead, you should mark all such classes as `[Obsolete]`, and add new classes for NPcap (even if those new classes are just copies of the old ones).

**Comment by chmorgan** [comment]
@lextm fortunately its just on master and shouldn't be pushed out through nuget yet so we can adjust and recover. Unfortunately its tough to get pre-screening on changes like this but if you are interested in being a co-maintainer of the project I'd gladly add you and include you in the process.

**Comment by chmorgan** [comment]
@lextm and it did occur to me that the rename could be highly disruptive and it would be an api breakage and I totally agree that we should keep and forward things over or keep and flag them as obsolete

**Comment by lextm** [comment]
@chmorgan But it is relatively easy for you to fix. Just copy the old files from a previous commit, and add them with ObsoleteAttribute tagged. Then everything should be back to normal.

I already have a bunch of projects to take care of, so I cannot be a maintainer of this repo, though you can always use `@lextm` to notify me if you need my input on something important.

**Pull request merged**
