### PR TITLE
Migrate PacketDotNet to .NET Standard 2

### PR DESCRIPTION
**Pull request by pluskal**
Add PacketDotNet as submodule because of cross references in tests...

### CODE REVIEW

**Comment by pluskal** [comment]
Git checkout needs to be recursive.

Change submodule url to chmorgan/packetnet repository (after merging [pullrequest](https://github.com/chmorgan/packetnet/pull/30)) or use Nuget package PacketDotNet instead of submodule.

**Comment by chmorgan** [comment]
Hi @pluskal I've updated AppVeyor and it looks like the build is getting further along but still not working correctly. Can you take a look at the build failures?

**Comment by pluskal** [comment]
Hi! @chmorgan I've tested it right now, and I do not have the issue. Looking at the AppVeyor log, I guess that it uses an older version of build engine: Build Engine version 14.0.25420.1, and it does not have support for .NET Standard 2.

**Comment by chmorgan** [comment]
@pluskal thoughts on what we should do? Its nice to keep the AppVeyor builds, .net standard 2 looks like the future of .net.

**Comment by pluskal** [comment]
@chmorgan I completely agree. I googled a bit a found this [this](https://stackoverflow.com/questions/46121024/build-on-appveyor-net-standard-2-0). You can try to modify it this way and see what happens. I do not have much experience with AppVeyor or .NET Standard 2, so I am afraid I would not be much help here. 

But, I've noticed slight performance improvement in your performance tests with .NET Standard 2.

**Pull request closed without merging**
