### PR TITLE
Try disabling PollFileDescriptor

### PR DESCRIPTION
**Pull request by chmorgan**

### CODE REVIEW

**Comment by kayoub5** [comment]
@chmorgan don't, file descriptor is needed for polling that don't block forever on Linux.
File descriptor polling is the right way, not just a workaround.

See https://www.tcpdump.org/manpages/pcap_get_selectable_fd.3pcap.html

**Comment by chmorgan** [comment]
Isn’t it ok to block forever now that pcap_breakloop() breaks out of the
loop?

**Comment by kayoub5** [comment]
As far as I know, pcap break loop is only for pcap dispatch. the fact that it works on get_next api is imlimentation depend.

**Comment by chmorgan** [comment]
@kayoub5 does this mean we can remove it in the case of the CaptureThread method at least? I've just been poking around looking for ways to improve performance.

**Comment by kayoub5** [comment]
that will work on the latest libpcap, slightly older versions have a broken break function that hangs until a packet is received.

**Comment by chmorgan** [comment]
@kayoub5 let me flag that with a comment then so we know to remove it in the future, I'll open a pr

**Pull request closed without merging**
