### PR TITLE
Restore WinDivert tests on CI

### PR DESCRIPTION
**Pull request by kayoub5**

### CODE REVIEW

**Comment by chmorgan** [comment]
@kayoub5 looks like this is still failing, maybe due to the secure boot being enabled for the windows install? That's why I had to disable the tests in the first place when moving to newer versions of windows.

**Comment by kayoub5** [comment]
@chmorgan right now WinDivert tests are not running on any CI.
Do you happen to recall what version of Windows / CI provider they used to work on?

**Comment by chmorgan** [comment]
@kayoub5 It looks like they were working on appveyor a while back with the vs2019 image, https://ci.appveyor.com/project/chmorgan/sharppcap/builds/36440374/job/n2l43p8yyaw8gpff/tests

I can't see history on azure-pipelines back far enough, they might not keep that data for OSS pipelines.

I wonder if something else was causing things to fail. Maybe try re-enabling the tests for the vs2019 appveyor image instead? It's possible it never would have worked on circleci if they had enabled secure boot.

**Comment by kayoub5** [comment]
@chmorgan I am not 100% convinced WinDivert is failing because of secure boot, because it just accidentally passed...

**Comment by kayoub5** [comment]
@basil00 Does `WinDivertSend` free the `pPacket` pointer, if not, when is it safe to free it?

**Comment by basil00** [comment]
The buffer is owned by the caller and `WinDivertSend` does not free it.  In fact, the buffer need not be heap memory, and can be stack or global memory.

But if it is heap memory, it is safe to free it after the call to `WinDivertSend` returns.

**Comment by chmorgan** [comment]
@kayoub5 so maybe the issue is that we aren't holding memory across the calls to WinDivertSend? What do you think the crash issue is caused by?

**Comment by kayoub5** [comment]
@chmorgan for this PR I just wanted to know one thing, why are WinDivert test crashing, and secure boot seems not to be the reason since WinDivert receive tests are passing for most CI services.

**Comment by kayoub5** [comment]
@chmorgan could we have this PR merged as is, and address the crash of `WinDivertSend` in another PR/issue ?

**Review by chmorgan — APPROVED** [review]

**Pull request merged**
