### PR TITLE
Convert targetframework for examples (except WinformsExample) from ne…

### PR DESCRIPTION
**Pull request by chmorgan**
…t48 to netcoreapp3.1

### CODE REVIEW

**Comment by chmorgan** [comment]
@kayoub5 strangely its the winpcap installations that are failing to find wpcap at runtime... thoughts?

**Comment by kayoub5** [comment]
Changes look good, but CI is failing

**Comment by chmorgan** [comment]
@kayoub5 yeah I know :-) But what the heck is going on? Why can't wpcap be found? It looks like the DllImport attributes are all still in place. Any ideas what might be going on?

**Comment by kayoub5** [comment]
@chmorgan It could be that WinPcap failed to install silently:
* Try to run the last master CI again
* Try to run this branch CI again
* 
Based on CI results:
* If problem happen in both, then something changed in CI provider
* If problem does not happen, then it was just a random failure
* If problem only happen in this branch, then something off

**Comment by chmorgan** [comment]
@kayoub5 well the winpcap install issue explains why it didn't work. I have no idea what's up there. Maybe the failure is buried in the logs somewhere, now that I know it can occur I'll go looking for it next time.

**Comment by chmorgan** [comment]
@kayoub5 I'll merge when you approve

**Review by kayoub5 — APPROVED** [review]

**Pull request merged**
