### PR TITLE
Load the Npcap DLL prior to the legacy WinPcap DLL.

### PR DESCRIPTION
**Pull request by hsluoyz**

### CODE REVIEW

**Comment by chmorgan** [comment]
Which one of these devices is the loopback one that was causing the issue with example6?

SharpPcap 4.2.0.0, Example6.DumpTCP.cs

The following devices are available on this machine:
----------------------------------------------------

0) rpcap://\Device\NPF_{CB4A447A-55AE-4D6F-A8C2-9D376B63860F} Network adapter 'M
S LoopBack Driver' on local host
1) rpcap://\Device\NPF_{D18235C1-D1B2-41CF-B0BA-4F80E8BA229C} Network adapter 'I
ntel(R) PRO/1000 MT Desktop Adapter' on local host
2) rpcap://\Device\NPF_{78032B7E-4968-42D3-9F37-287EA86C0AAA} Network adapter 'A
syncMac Adapter' on local host
3) rpcap://\Device\NPF_NdisWanIp Network adapter 'NdisWan Adapter' on local host

4) rpcap://\Device\NPF_NdisWanBh Network adapter 'NdisWan Adapter' on local host

5) rpcap://\Device\NPF_NdisWanIpv6 Network adapter 'NdisWan Adapter' on local ho
st

**Comment by chmorgan** [comment]
Also, why do we need to set the dll directory? I thought system installed dlls didn't require any path manipulation.

**Comment by hsluoyz** [comment]
> Which one of these devices is the loopback one that was causing the issue with example6?

it's possible to be ``MS LoopBack Driver``.

**Comment by hsluoyz** [comment]
> Also, why do we need to set the dll directory? I thought system installed dlls didn't require any path manipulation.

Npcap installs its DLLs to: ``C:\Windows\System32\Npcap`` by default. Unfortunately, Windows doesn't scan the sub folders of System32. This is why we need the path manipulation. Nmap, Wireshark already did this manipulation.

**Pull request closed without merging**
