### PR TITLE
Add support for more configuration options. Allow detecting partially failed configuration.

### PR DESCRIPTION
**Pull request by kayoub5**
@chmorgan I expect some tests to fail on the first run due to platform support (I need them to fail on purpose to see what platform can do what).
regardless a review of the idea/concept would be appreciated.

### CODE REVIEW

**Comment by chmorgan** [comment]
@kayoub5 yeah I think this could improve the clarity of the configuration. I've got some changes related to timestamp coming, let me open up a PR so you can see how they look.

**Comment by kayoub5** [comment]
@chmorgan ready for review

**Comment by chmorgan** [comment]
@kayoub5 where is StrictConfig defined?

**Review by chmorgan — APPROVED** [review]
Must have missed the StrictConfig definition before. Looks like a good improvement and I like the use of the function arguments, this looks like a pretty ideal case for that.

**Pull request merged**
